config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :cities do
    member do
      post :update_temp
    end 
  end 
  
    namespace :api, :defaults => { :format => :json } do
      namespace :v1 do
        get "/trains"  => "trains#index", :as => :trains
        get "/trains/:train_number" => "trains#show", :as => :train
   
        get "/reservations/:booking_code" => "reservations#show", :as => :reservation
        post "/reservations" => "reservations#create", :as => :create_reservations
        patch "/reservations/:booking_code" => "reservations#update", :as => :update_reservation
        delete "/reservations/:booking_code" => "reservations#destroy", :as => :cancel_reservation
      end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  
   validates_presence_of :train_id, :seat_number, :booking_code
   validates_uniqueness_of :seat_number, :scope => :train_id
 
   belongs_to :train
 
   before_validation :generate_booking_code, :on => :create
 
   def generate_booking_code
     self.booking_code = SecureRandom.uuid
   end

end

app/models/train.rb
class Train < ApplicationRecord
  
  validates_presence_of :number
  has_many :reservations
  
  def available_seats
    ["1A", "1B", "1C", "1D"]
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end 
  
  def update_temp
      city = City.find(params[:id])
  
      response = RestClient.get "http://v.juhe.cn/weather/index", 
                                :params => { :cityname => city.juhe_id, :key => "802a20f914380aa9c238bba1b0b8bec5" }
      data = JSON.parse(response.body)
  
      city.update( :current_temp => data["result"]["sk"]["temp"] )
  
      redirect_to cities_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/index.html.erb
<table class="table">
<tr>
  <th>Juhe ID</th>
  <th>Province</th>
  <th>City</th>
  <th>District</th>
  <th>Temp</th>
</tr>
<% @cities.each do |city| %>
  <tr>
    <td><%= city.juhe_id %></td>
    <td><%= city.province %></td>
    <td><%= city.city %></td>
    <td><%= city.district %></td>
    <td>
      <%= city.current_temp %>
      <%= link_to "更新温度", update_temp_city_path(city), :method => :post %>
    </td>

  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>欢迎查阅天气情况</h1>

<%= link_to "进入各城市天气情况", cities_path %>